Holiday/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Holiday.DataBaseContext;
using Holiday.Models;
using Holiday.Services.Interfaces;
using Holiday.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Holiday.Controllers
{
  
    public class EmployeesController : Controller
    {
        private readonly HolidayContext _context;
     
        public EmployeesController(HolidayContext context)
        {
      
            _context = context;
        }

        // GET: Employees
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index1()
        {
            return View(await _context.Employees.ToListAsync());
        }
        // GET: Employees/Details/5
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }
        [Authorize(Roles = "HumanResource")]

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FirstName,LastName,HolidayType,NumberOfDays,Date,NumberOfDaysConsumed,NumberOfDaysLeft")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> Edit(string employeeId, [Bind("EmployeeId,FirstName,LastName,HolidayType,NumberOfDays,Date,NumberOfDaysConsumed,NumberOfDaysLeft")] Employee employee)
        {
            if (employeeId != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }



        // GET: Employees/Delete/5
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "HumanResource")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(string id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }
    }
}

Holiday/Controllers/VacantionRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Holiday.DataBaseContext;
using Holiday.Models;
using Holiday.Repositories.Interfaces;
using Holiday.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Holiday.Controllers
{
    public class VacantionRequestsController : Controller
    {
        private readonly HolidayContext _context;
  

        public VacantionRequestsController(HolidayContext context)
        {
           
            _context = context;
        }
        // GET: VacantionRequests
        [Authorize(Roles="Operational,Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.VacantionRequests.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index1()
        {
            return View(await _context.VacantionRequests.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index2()
        {
            return View(await _context.VacantionRequests.ToListAsync());
        }

        [Authorize(Roles = "Operational,Admin")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var holidayRequest = await _context.VacantionRequests
                .FirstOrDefaultAsync(m => m.VacantionRequestId == id);
            if (holidayRequest == null)
            {
                return NotFound();
            }

            return View(holidayRequest);
        }


        // GET: VacantionRequests/Create
        [Authorize(Roles = "Operational")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: VacantionRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VacantionRequestId,FirstName,LastName,Type,StartDate,NoOfDays,Cause")] VacantionRequest vacantionRequest)
        {
            if (ModelState.IsValid)
            {
          
                _context.Add(vacantionRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vacantionRequest);
        }

        // GET: VacantionRequests/Edit/5
        [Authorize(Roles = "Operational")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacantionRequest = await _context.VacantionRequests.FindAsync(id);
            if (vacantionRequest == null)
            {
                return NotFound();
            }
            return View(vacantionRequest);
        }

        // POST: VacantionRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operational")]
        public async Task<IActionResult> Edit(string id, [Bind("VacantionRequestId,FirstName,LastName,Type,StartDate,NoOfDays,Cause")] VacantionRequest vacantionRequest)
        {
            if (id != vacantionRequest.VacantionRequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vacantionRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VacantionRequestExists(vacantionRequest.VacantionRequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vacantionRequest);
        }

        // GET: VacantionRequests/Delete/5
        [Authorize(Roles = "Operational,Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacantionRequest = await _context.VacantionRequests
                .FirstOrDefaultAsync(m => m.VacantionRequestId == id);
            if (vacantionRequest == null)
            {
                return NotFound();
            }

            return View(vacantionRequest);
        }

        // POST: VacantionRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operational,Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var vacantionRequest = await _context.VacantionRequests.FindAsync(id);
            _context.VacantionRequests.Remove(vacantionRequest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VacantionRequestExists(string id)
        {
            return _context.VacantionRequests.Any(e => e.VacantionRequestId == id);
        }
    }
}

Holiday/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Holiday</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Holiday</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HumanResource">HumanResource</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="OperationalRole">Operational</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Admin">Admin</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="VacantionRequests" asp-action="Index">Create a request</a>
        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Holiday - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("head", required: false)
</body>
</html>